package com.contafood.util;

public enum Provincia {

    AGRIGENTO("Agrigento"),
    ALESSANDRIA("Alessandria"),
    ANCONA("Ancona"),
    AOSTA("Aosta"),
    AREZZO("Arezzo"),
    ASCOLI_PICENO("Ascoli Piceno"),
    ASTI("Asti"),
    AVELLINO("Avellino"),
    BARI("Bari"),
    BARLETTA_ANDRIA_TRANI("Barletta-Andria-Trani"),
    BELLUNO("Belluno"),
    BENEVENTO("Benevento"),
    BERGAMO("Bergamo"),
    BIELLA("Biella"),
    BOLOGNA("Bologna"),
    BOLZANO("Bolzano"),
    BRESCIA("Brescia"),
    BRINDISI("Brindisi"),
    CAGLIARI("Cagliari"),
    CALTANISSETTA("Caltanissetta"),
    CAMPOBASSO("Campobasso"),
    CARBONIA_IGLESIAS("Carbonia-Iglesias"),
    CASERTA("Caserta"),
    CATANIA("Catania"),
    CATANZARO("Catanzaro"),
    CHIETI("Chieti"),
    COMO("Como"),
    COSENZA("Cosenza"),
    CREMONA("Cremona"),
    CROTONE("Crotone"),
    CUNEO("Cuneo"),
    ENNA("Enna"),
    FERMO("Fermo"),
    FERRARA("Ferrara"),
    FIRENZE("Firenze"),
    FOGGIA("Foggia"),
    FORLI_CESENA("Forli-Cesena"),
    FROSINONE("Frosinone"),
    GENOVA("Genova"),
    GORIZIA("Gorizia"),
    GROSSETO("Grosseto"),
    IMPERIA("Imperia"),
    ISERNIA("Isernia"),
    LA_SPEZIA("La Spezia"),
    L_AQUILA("L'Aquila"),
    LATINA("Latina"),
    LECCE("Lecce"),
    LECCO("Lecco"),
    LIVORNO("Livorno"),
    LODI("Lodi"),
    LUCCA("Lucca"),
    MACERATA("Macerata"),
    MANTOVA("Mantova"),
    MASSA_CARRARA("Massa-Carrara"),
    MATERA("Matera"),
    MESSINA("Messina"),
    MILANO("Milano"),
    MODENA("Modena"),
    MONZA_BRIANZA("Monza Brianza"),
    NAPOLI("Napoli"),
    NOVARA("Novara"),
    NUORO("Nuoro"),
    OLBIA_TEMPIO("Olbia-Tempio"),
    ORISTANO("Oristano"),
    PADOVA("Padova"),
    PALERMO("Palermo"),
    PARMA("Parma"),
    PAVIA("Pavia"),
    PERUGIA("Perugia"),
    PESARO_URBINO("Pesaro Urbino"),
    PESCARA("Pescara"),
    PIACENZA("Piacenza"),
    PISA("Pisa"),
    PISTOIA("Pistoia"),
    PORDENONE("Pordenone"),
    POTENZA("Potenza"),
    PRATO("Prato"),
    RAGUSA("Ragusa"),
    RAVENNA("Ravenna"),
    REGGIO_CALABRIA("Reggio Calabria"),
    REGGIO_EMILIA("Reggio Emilia"),
    RIETI("Rieti"),
    RIMINI("Rimini"),
    ROMA("Roma"),
    ROVIGO("Rovigo"),
    SALERNO("Salerno"),
    MEDIO_CAMPIDANO("Medio Campidano"),
    SASSARI("Sassari"),
    SAVONA("Savona"),
    SIENA("Siena"),
    SIRACUSA("Siracusa"),
    SONDRIO("Sondrio"),
    TARANTO("Taranto"),
    TERAMO("Teramo"),
    TERNI("Terni"),
    TORINO("Torino"),
    OGLIASTRA("Ogliastra"),
    TRAPANI("Trapani"),
    TRENTO("Trento"),
    TREVISO("Treviso"),
    TRIESTE("Trieste"),
    UDINE("Udine"),
    VARESE("Varese"),
    VENEZIA("Venezia"),
    VERBANO_CUSIO_OSSOLA("Verbano-Cusio-Ossola"),
    VERCELLI("Vercelli"),
    VERONA("Verona"),
    VIBO_VALENTIA("Vibo Valentia"),
    VICENZA("Vicenza"),
    VITERBO("Viterbo");

    private String label;

    Provincia(String label) {
        this.label = label;
    }

    public String getLabel() {
        return label;
    }
}
